name: Deploy testing

on:
  workflow_dispatch:

jobs:
  deploy_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: sed -i "s|0.0.0|${GITHUB_REF}|" src/lib/version.ts
      - run: sed -i "s|abcdef123456|${GITHUB_SHA}|" src/lib/version.ts
      - run: npm ci
      - run: npm install @angular/cli
      - run: npx ng build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ctrl-b357a
          expires: 7d
          channelId:
