name: Deploy staging test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy'
        required: true
        default: 'main'
      cloudflare-branch:
        description: 'Cloudflare branch'
        required: true
        default: 'main'
      project-name:
        description: 'The Project Name'
        required: true
        default: 'ctrl-app'

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: sed -i "s|0.0.0|${GITHUB_REF}|" src/lib/version.ts
      - run: sed -i "s|abcdef123456|${GITHUB_SHA}|" src/lib/version.ts
      - run: npm install
      - run: npm install @angular/cli
      - run: npx ng build --localize
      - run: cp _redirects dist/ctrl/_redirects
      - run: cp -ru dist/ctrl/en-US/assets dist/ctrl
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '3'
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Use branch name to indicate Cloudflare environment: (main | staging)
          # Cloudflare does not deploy by itself so the value is only used to
          # determine the target environment according to defined rules.
          command: pages deploy dist/ctrl --project-name=${{ github.event.inputs.project-name }} --branch=${{ github.event.inputs.cloudflare-branch }}
